
from pathlib import Path
import json, bpy

script_folder = Path(__file__).parent

DEFAULT_DIRECTORIES = {
    "directory_med2": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Medieval II Total War",
    "directory_iwte": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Medieval II Total War\\mods",
    "directory_mod_list": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Medieval II Total War\\mods",
    "directory_mod_data": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Medieval II Total War\\mods",
    "directory_models": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Medieval II Total War\\mods",
    "directory_settlements": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Medieval II Total War\\mods",
    "directory_unit_export": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Medieval II Total War\\mods",
    "directory_iwte_task_template": ""
}

DEFAULT_MENU_SETTINGS = {
    "hide_toggle": False,
    "use_existing": False,
    "frame_toggle": False,
    "textured_toggle": False,
    "use_existing_settlement": False
}

# Files that ship empty since their content is generated by "Read Mod Data".
DEFAULT_DATA_FILES = {
    "directories.json": DEFAULT_DIRECTORIES,
    "menu_settings.json": DEFAULT_MENU_SETTINGS,
    "available_factions.json": {},
    "unit_dictionary.json": {},
    "model_dictionary.json": {},
    "settlement_pkgs.json": {},
    "settlement_folders.json": [],
    "attachment_dictionary.json": [],
}

def ensureDataFiles():
    text_folder = script_folder/'text'
    text_folder.mkdir(exist_ok=True)
    for file_name, default_content in DEFAULT_DATA_FILES.items():
        file_path = text_folder/file_name
        if file_path.exists():
            continue
        with open(file_path, 'w') as default_output:
            json.dump(default_content, default_output, indent=2)

def saveFolderPaths():
    mod_list = bpy.context.scene.med2_toolkit_reader.list_holder
    if bpy.context.scene.med2_toolkit_reader.mods_filtered != "custom":
        mod_data = bpy.context.scene.med2_toolkit_reader.mods_filtered
        temp_list = mod_list.split(',')
        temp_list.remove(mod_data)
        temp_list.insert(0, mod_data)
        mod_list = ','.join(temp_list)
    else:
        mod_data = bpy.context.scene.med2_toolkit_reader.directory_mod_data
    # start from the existing file so extra keys (last-used defaults stored
    # with storeValue) survive the rewrite
    try:
        with open(script_folder/('text/directories.json'), 'r') as directories_input:
            directories = json.load(directories_input)
    except (OSError, ValueError):
        directories = {}
    directories.update({
        "directory_med2": bpy.context.scene.med2_toolkit_reader.directory_med2,
        "directory_iwte": bpy.context.scene.med2_toolkit_reader.directory_iwte,
        "directory_mod_list": mod_list,
        "directory_mod_data": mod_data,
        "directory_models": bpy.context.scene.med2_toolkit_reader.directory_models,
        "directory_settlements": bpy.context.scene.med2_toolkit_reader.directory_settlements,
        "directory_unit_export": bpy.context.scene.med2_toolkit_reader.directory_unit_export,
        "directory_iwte_task_template": bpy.context.scene.med2_toolkit_reader.directory_iwte_task_template
    })
    with open(script_folder/('text/directories.json'), 'w') as directories_output:
        json.dump(directories, directories_output, indent=2)
    return{"FINISHED"}


def loadStoredValue(key, default=""):
    """Read one extra value (e.g. a last-used default) from directories.json."""
    try:
        with open(script_folder/('text/directories.json'), 'r') as directories_input:
            return json.load(directories_input).get(key, default)
    except (OSError, ValueError):
        return default


def storeValue(key, value):
    """Persist one extra value into directories.json."""
    try:
        with open(script_folder/('text/directories.json'), 'r') as directories_input:
            directories = json.load(directories_input)
    except (OSError, ValueError):
        directories = {}
    directories[key] = value
    with open(script_folder/('text/directories.json'), 'w') as directories_output:
        json.dump(directories, directories_output, indent=2)


def saveSettings():
    settings = {
        "hide_toggle" : bpy.context.scene.med2_toolkit_units.hide_toggle,
        "use_existing" : bpy.context.scene.med2_toolkit_units.use_existing,
        "frame_toggle" : bpy.context.scene.med2_toolkit_units.frame_toggle,
        "textured_toggle" : bpy.context.scene.med2_toolkit_units.textured_toggle,
        "use_existing_settlement" : bpy.context.scene.med2_toolkit_settlements.use_existing_settlement
    }
    with open(script_folder/('text/menu_settings.json'), 'w') as settings_output:
        json.dump(settings, settings_output, indent=2)
    return{"FINISHED"}