import bpy
from pathlib import Path
import os

def tex_to_asset(file_path):
    normal_suffix = ['_normal.dds', '_norm.dds', '_nrm.dds', '_bump.dds']
    normal_textures = []
    textures = []

    for image_file in os.listdir(file_path):
        # print(image_file)
        if image_file[-4:] == ".dds":
            if any(suffix in image_file for suffix in normal_suffix):
                normal_textures.append(image_file)
                print("normal texture type")
            else:
                textures.append(image_file)

    for texture in textures:
        material = bpy.data.materials.new(texture.replace(".dds", "_dds"))
        # Setup material mode and keywords
        material.use_nodes = True
        material.preview_render_type = 'FLAT'
        material.blend_method = 'CLIP'
        material.use_backface_culling = True
        nodes = material.node_tree.nodes
        new_link = material.node_tree.links.new

        # Defining nodes
        shader_node = material.node_tree.nodes["Principled BSDF"]
        shader_node.inputs['Metallic'].default_value = 0
        texture_image = nodes.new("ShaderNodeTexImage")
        texture_image.name = 'Diffuse Texture'
        texture_image.location = (-506, 444)
        texture_image.image = bpy.data.images.load(file_path+texture)
        # Linking nodes: colour -> shader; alpha -> shader
        new_link(shader_node.inputs[0], texture_image.outputs[0])
        new_link(shader_node.inputs[4], texture_image.outputs[1])
        # Normal setup
        rgb_curve = nodes.new("ShaderNodeRGBCurve")
        rgb_curve.location = (-506, 124)
        # Flip the green channel
        curve_g = rgb_curve.mapping.curves[1]
        curve_g.points[0].location = (0, 1)
        curve_g.points[1].location = (1, 0)
        normal_map = nodes.new("ShaderNodeNormalMap")
        normal_map.location = (-206, 124)
        normal_image = nodes.new("ShaderNodeTexImage")
        normal_image.name = 'Normal Texture'
        normal_image.location = (-836, 124)
        # Check Normal texture
        for suffix in normal_suffix:
            normal_texture = texture.replace(".dds", suffix)
            if texture.replace(".dds", suffix) in normal_textures:
                normal_image.image = bpy.data.images.load(file_path+normal_texture)
                normal_image.image.colorspace_settings.name = 'Non-Color'
                # Linking nodes: normal -> curves -> normal map -> shader
                new_link(shader_node.inputs[5], normal_map.outputs[0])
                break
        new_link(rgb_curve.inputs[1], normal_image.outputs[0])
        new_link(normal_map.inputs[1], rgb_curve.outputs[0])
        # Mark as asset
        material.asset_mark()
        material.asset_generate_preview()
        material.asset_data.description = ("Generated by Med2 Toolkit")